name: test

on:
  push:
    paths:
      - "generate_readme/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # check only. not commit.
      - name: Generate README.md
        run: ./generate_readme/main.sh
      - run: cat README.md
